modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "hextweaks"
version = "${version}"
displayName = "Hex Tweaksd"
authors = "Me!"
description = '''
Opionated changes to hexcasting
'''
#logoFile = ""

[[dependencies.hextweaks]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hextweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hextweaks]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hextweaks]]
modId = "computercraft"
mandatory = false
versionRange = "[1.109.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hextweaks]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.11.1,)"
ordering = "AFTER"
side = "BOTH"