name: Run Gradle on commit
on: [push]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build
    
    - name: 'Upload Forge Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: forge
        path: forge/build/libs
    - name: "Upload Fabric Artifact"
      uses: actions/upload-artifact@v3
      with:
        name: fabric
        path: fabric/build/libs